# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
