# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20180904_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='id',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='pk_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
