# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_product_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
