# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20181007_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
