# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='pk_id',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
