# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='hostname',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
