# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-27 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20181014_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='mirror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
